### ISSUE TITLE
I shouldn’t be here.

### ISSUE THREAD

**Issue by yangchongduo** [rookLab/react-component-caching#49]
https://github.com/rookLab/react-component-caching/blob/f4f1a273cea7ba06b6886f538169dd4511d130c4/src/server/ReactPartialRenderer.js#L620

**Comment by yangchongduo** [comment]
Every rendering
```
Var loadedTemplates = {};
```
Are all local variables

**Comment by yangchongduo** [comment]
Above is the cache
Below is no cache

The average rendering time for 2606 requests is: 0.93 ms
The average rendering time for 2774 requests is: 0.40 ms

 Mean latency:        67.9 ms
 Mean latency:        46.3 ms

**Comment by atlas1119** [comment]
yes，may be not help
